default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/location_share' %>


development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres@localhost/location_share_test' %>

production:
  <<: *default
